# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

KEYSTORE = ENV["APP_KEYSTORE"]
KEYSTORE_PASS = ENV["APP_KEYSTORE_PASS"]
KEY_ALIAS = ENV["APP_KEY_ALIAS"]
KEY_PASSWORD = ENV["APP_KEY_PASSWORD"]

platform :android do

  desc "Build a new release and upload it to Play/Github"
  lane :release do

    # Build it all
    gradle(
      task: "clean assembleRelease",
      properties: {
        "android.injected.signing.store.file" => KEYSTORE,
        "android.injected.signing.store.password" => KEYSTORE_PASS,
        "android.injected.signing.key.alias" => KEY_ALIAS,
        "android.injected.signing.key.password" => KEY_PASSWORD,
      },
      print_command: false
    )
    #upload_to_play_store
  end
end
